
stages:
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/

services:
  - docker:dind

build:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

deploy:
  stage: deploy
  script:
    - kubectl config set-cluster my-cluster --server=https://your-kubernetes-server --certificate-authority=/path/to/your/ca.crt
    - kubectl config set-credentials my-user --username=your-username --password=your-password
    - kubectl config set-context my-cluster --cluster=my-cluster --user=my-user --namespace=your-namespace
    - kubectl config use-context my-cluster
    - kubectl set image deployment/your-deployment your-container=$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
